# Generated by Django 2.2.12 on 2022-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0002_contactos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='Facebook',
            new_name='social',
        ),
    ]
